import { PayrollRepository } from '../repositories/PayrollRepository';
import { Employee } from '@/app/api/models/Employee';
import { Attendance } from '@/app/api/models/Attendance';
import { Leave } from '@/app/api/models/Leave';
import { User } from '@/app/api/models/User';
import { AuditLog } from '@/app/api/models/AuditLog';
import { sendEmail } from '../../../utils/email';
import { SystemNotificationService } from '../../../services/systemNotificationService';

function buildSalaryEmailHTML(recipientName: string, month: string, detailsHtml: string) {
  return `
<!DOCTYPE html>
<html>
<body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed; background-color: #f8fafc;">
    <tr>
      <td align="center" style="padding: 30px 10px;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #ffffff; border-radius: 20px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
          <tr>
            <td align="center" style="padding: 35px 40px; background: linear-gradient(135deg, #059669 0%, #10b981 100%); text-align: left;">
              <span style="font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; color: #a7f3d0;">Enterprise HR Payroll</span>
              <h1 style="margin: 6px 0 0; font-size: 22px; font-weight: 800; color: #ffffff; letter-spacing: -0.5px;">SALARY DISBURSED</h1>
            </td>
          </tr>
          <tr>
            <td align="left" style="padding: 40px; background-color: #ffffff;">
              <p style="margin: 0 0 16px; font-size: 15px; color: #0f172a; line-height: 1.6;">Dear <strong>${recipientName}</strong>,</p>
              <p style="margin: 0 0 24px; font-size: 14px; color: #334155; line-height: 1.6;">We are pleased to inform you that your monthly salary payout for <strong>${month}</strong> has been successfully processed and disbursed via direct bank transfer to your registered account.</p>
              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
                ${detailsHtml}
              </table>
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td align="center" style="padding-top: 10px; padding-bottom: 10px;">
                    <a href="http://localhost:3000/" target="_blank" style="display: inline-block; padding: 12px 24px; background-color: #059669; color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px;">View Payslip Portal</a>
                  </td>
                </tr>
              </table>
              <p style="margin: 24px 0 0; font-size: 13px; color: #64748b; line-height: 1.6;">Best regards,<br/><strong style="color: #059669;">Finance & Payroll Team</strong></p>
            </td>
          </tr>
          <tr>
            <td align="center" style="padding: 24px 40px; background-color: #f8fafc; border-top: 1px solid #f1f5f9;">
              <p style="margin: 0 0 6px; font-size: 11px; color: #475569; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;">Enterprise Systems Ltd</p>
              <p style="margin: 0; font-size: 10px; color: #94a3b8; line-height: 1.5;">This email is auto-generated by the corporate payroll system. Please do not reply directly to this message.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

export class PayrollService {
  static async getPayrolls(companyId?: string, employeeEmail?: string) {
    const filter: any = {};
    if (companyId) {
      filter.companyId = companyId;
    }
    if (employeeEmail) {
      filter.employee = employeeEmail;
    }
    const payrolls = await PayrollRepository.findAll(filter);
    return { data: payrolls, status: 200 };
  }

  static async createPayroll(data: any, companyId: string) {
    if (!data.employee || !data.month || data.basic === undefined) {
      return { error: 'Missing required fields (employee, month, basic)', status: 400 };
    }

    const newPayroll = await PayrollRepository.create({ ...data, companyId });
    return { message: 'Payroll record created successfully', payroll: newPayroll, status: 201 };
  }

  static async generatePayroll(month: string, companyId: string) {
    if (!month) {
      return { error: 'Month parameter is required', status: 400 };
    }

    const monthMap: Record<string, string> = {
      'january': '01', 'february': '02', 'march': '03', 'april': '04', 'may': '05', 'june': '06',
      'july': '07', 'august': '08', 'september': '09', 'october': '10', 'november': '11', 'december': '12',
      'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'jun': '06',
      'jul': '07', 'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12'
    };

    const parts = month.toLowerCase().split(' ');
    const yearStr = parts[1] || '2026';
    const monthName = parts[0] || 'may';
    const monthNum = monthMap[monthName] || '05';
    const datePrefix = `${yearStr}-${monthNum}`;

    const employees = await Employee.find({ status: 'Active', companyId });
    if (employees.length === 0) {
      return { message: 'No active employees found to process', status: 404 };
    }

    const generatedRecords = [];

    for (const emp of employees) {
      const attendanceRecords = await Attendance.find({
        name: emp.fullName,
        date: { $regex: `^${datePrefix}` },
        companyId
      });

      const leaveRecords = await Leave.find({
        employee: emp.email,
        status: 'Approved',
        date: { $regex: `^${datePrefix}` },
        companyId
      });

      const totalDaysInMonth = 30;
      let presentDays = 0;
      let halfDays = 0;
      let lateDays = 0;
      let absentDays = 0;
      let overtimeHours = 0;

      attendanceRecords.forEach(att => {
        const status = att.status.toLowerCase();
        if (status === 'present') {
          presentDays++;
        } else if (status === 'half-day' || status === 'half day') {
          halfDays++;
        } else if (status === 'late') {
          lateDays++;
          presentDays++;
        } else if (status === 'absent') {
          absentDays++;
        }

        if (att.duration) {
          const match = att.duration.match(/(\d+)h/);
          if (match) {
            const hours = parseInt(match[1], 10);
            if (hours > 9) {
              overtimeHours += (hours - 9);
            }
          }
        }
      });

      const approvedLeaveDays = leaveRecords.length;
      const unpaidLeaves = Math.max(0, absentDays - approvedLeaveDays) + (halfDays * 0.5);

      const struct = emp.salaryStructure || {
        basic: 30000,
        hra: 10000,
        allowance: 5000,
        bonus: 0,
        pf: 3600,
        esi: 1000,
        tax: 2000,
        otherDeductions: 0,
        net: 38400
      };

      const dailyRate = (struct.basic + struct.hra + struct.allowance) / totalDaysInMonth;
      const leaveDeductions = Math.round(dailyRate * unpaidLeaves);
      const overtimePay = overtimeHours * 300;
      const lateDeductions = Math.max(0, lateDays - 2) * 100;

      const basicPay = Math.max(0, struct.basic - leaveDeductions);
      const gross = basicPay + struct.hra + struct.allowance + struct.bonus + overtimePay;

      const employeePF = Math.round(basicPay * 0.12);
      const employeeESI = Math.round(gross * 0.0075);

      let calculatedTDS = 0;
      if (gross > 100000) {
        calculatedTDS = Math.round(gross * 0.10);
      } else if (gross > 50000) {
        calculatedTDS = Math.round(gross * 0.05);
      } else {
        calculatedTDS = struct.tax || 0;
      }

      const totalDeductions = employeePF + employeeESI + calculatedTDS + lateDeductions + struct.otherDeductions;
      const net = Math.max(0, gross - totalDeductions);

      await PayrollRepository.deleteOne({
        employee: emp.email,
        month,
        companyId,
        status: { $in: ['Draft', 'Pending Approval', 'Approved'] }
      });

      const payrollRecord = await PayrollRepository.create({
        employee: emp.email,
        employeeName: emp.fullName,
        month,
        basic: basicPay,
        hra: struct.hra,
        allowance: struct.allowance,
        bonus: struct.bonus,
        overtime: overtimePay,
        pf: employeePF,
        esi: employeeESI,
        tax: calculatedTDS,
        otherDeductions: lateDeductions + struct.otherDeductions,
        gross,
        net,
        workingDays: Math.max(0, totalDaysInMonth - unpaidLeaves),
        leaveDeductions,
        status: 'Draft',
        companyId
      });

      generatedRecords.push(payrollRecord);
    }

    return {
      message: `Bulk payroll generated successfully for ${generatedRecords.length} active employees`,
      count: generatedRecords.length,
      records: generatedRecords,
      status: 200
    };
  }

  static async updatePayroll(id: string, data: any, companyId: string) {
    const originalPayroll = await PayrollRepository.findById(id);
    if (!originalPayroll) {
      return { error: 'Payroll record not found', status: 404 };
    }
    if (originalPayroll.companyId !== companyId) {
      return { error: 'Forbidden: You do not own this record', status: 403 };
    }

    const updatedPayroll = await PayrollRepository.updateById(id, data);
    if (!updatedPayroll) {
      return { error: 'Payroll record not found', status: 404 };
    }

    if (updatedPayroll.status === 'Paid' && originalPayroll?.status !== 'Paid' && updatedPayroll.employee && updatedPayroll.employee.includes('@')) {
      try {
        // Add System Notification
        SystemNotificationService.createNotification({
          companyId,
          userId: updatedPayroll.employee,
          title: 'Salary Disbursed',
          content: `Your monthly salary payout for ${updatedPayroll.month} has been disbursed. Net: ₹${updatedPayroll.net.toLocaleString()}`,
          type: 'payroll',
          targetPage: 'payroll'
        }).catch(err => console.error('Failed to trigger payroll system notification:', err));

        const totalDeductions = (updatedPayroll.pf || 0) + 
                               (updatedPayroll.esi || 0) + 
                               (updatedPayroll.tax || 0) + 
                               (updatedPayroll.otherDeductions || 0) + 
                               (updatedPayroll.leaveDeductions || 0);

        const allowances = (updatedPayroll.hra || 0) + (updatedPayroll.allowance || 0);

        const detailsHtml = `
          <tr>
            <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 40%;">Employee Name</td>
            <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${updatedPayroll.employeeName}</td>
          </tr>
          <tr>
            <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Payout Month</td>
            <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${updatedPayroll.month}</td>
          </tr>
          <tr>
            <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Base Earnings (Basic)</td>
            <td style="font-size: 12px; color: #334155; padding-bottom: 8px;">₹${updatedPayroll.basic.toLocaleString()}</td>
          </tr>
          ${allowances > 0 ? `
          <tr>
            <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">HRA & Allowances</td>
            <td style="font-size: 12px; color: #334155; padding-bottom: 8px;">₹${allowances.toLocaleString()}</td>
          </tr>` : ''}
          ${updatedPayroll.bonus > 0 ? `
          <tr>
            <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Incentive / Bonus</td>
            <td style="font-size: 12px; color: #16a34a; padding-bottom: 8px; font-weight: bold;">₹${updatedPayroll.bonus.toLocaleString()}</td>
          </tr>` : ''}
          ${totalDeductions > 0 ? `
          <tr>
            <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Total Deductions</td>
            <td style="font-size: 12px; color: #dc2626; padding-bottom: 8px;">-₹${totalDeductions.toLocaleString()}</td>
          </tr>` : ''}
          <tr style="border-top: 1px solid #bbf7d0; padding-top: 8px;">
            <td style="font-size: 12px; font-weight: 800; color: #047857; padding-top: 8px;">Net Disbursed</td>
            <td style="font-size: 13px; font-weight: 900; color: #047857; padding-top: 8px;">₹${updatedPayroll.net.toLocaleString()}</td>
          </tr>
        `;

        const emailSubject = `Salary Disbursed: Payout Receipt for ${updatedPayroll.month}`;
        const emailText = `Dear ${updatedPayroll.employeeName},\n\nWe are pleased to inform you that your monthly salary payout for ${updatedPayroll.month} has been successfully processed and disbursed. Net Pay: ₹${updatedPayroll.net.toLocaleString()}.\n\nBest regards,\nFinance & Payroll Team`;
        const emailHtml = buildSalaryEmailHTML(updatedPayroll.employeeName, updatedPayroll.month, detailsHtml);

        sendEmail({
          to: updatedPayroll.employee,
          subject: emailSubject,
          text: emailText,
          html: emailHtml
        }).catch(emailErr => {
          console.error('Failed to send salary disbursal email:', emailErr);
        });
      } catch (prepErr) {
        console.error('Failed to prepare salary disbursal email:', prepErr);
      }
    }

    try {
      await AuditLog.create({
        action: 'Payroll Status Update',
        performedBy: 'admin@hr.com',
        details: `Updated payroll status for ${updatedPayroll.employeeName} (${updatedPayroll.month}) from '${originalPayroll?.status || 'Unknown'}' to '${updatedPayroll.status}'`,
        ipAddress: '127.0.0.1',
        companyId
      });
    } catch (logError) {
      console.error('Failed to write audit log:', logError);
    }

    return { message: 'Payroll record updated successfully', payroll: updatedPayroll, status: 200 };
  }

  static async deletePayroll(id: string, companyId: string) {
    const originalPayroll = await PayrollRepository.findById(id);
    if (!originalPayroll) {
      return { error: 'Payroll record not found', status: 404 };
    }
    if (originalPayroll.companyId !== companyId) {
      return { error: 'Forbidden: You do not own this record', status: 403 };
    }

    await PayrollRepository.deleteById(id);
    return { message: 'Payroll record deleted successfully', status: 200 };
  }

  static async getBankDetails(email: string, companyId: string) {
    if (!email) {
      return { error: 'Email parameter is required', status: 400 };
    }

    const user = await User.findOne({ email, companyId });
    if (!user) {
      return { error: 'User not found', status: 404 };
    }

    return { bankDetails: user.bankDetails || null, status: 200 };
  }

  static async updateBankDetails(email: string, bankDetails: any, companyId: string) {
    if (!email || !bankDetails) {
      return { error: 'Missing required fields (email, bankDetails)', status: 400 };
    }

    const { bankName, accountNumber, ifscCode, accountHolderName } = bankDetails;

    if (!bankName || !accountNumber || !ifscCode || !accountHolderName) {
      return { error: 'All bank details fields are required', status: 400 };
    }

    let user = await User.findOne({ email, companyId });

    if (!user) {
      // Find company code/name from Admin of this companyId
      const admin = await User.findOne({ companyId, role: 'Admin' });
      const companyCode = admin?.companyCode || 'hrcore';
      const companyName = admin?.companyName || 'Corporate';

      user = await User.create({
        fullName: accountHolderName || 'John Doe',
        email,
        companyName,
        companyCode,
        companyId,
        role: 'Employee',
        password: 'demo_placeholder_password',
        bankDetails: {
          bankName,
          accountNumber,
          ifscCode,
          accountHolderName
        }
      });
    } else {
      user.bankDetails = {
        bankName,
        accountNumber,
        ifscCode,
        accountHolderName
      };
      await user.save();
    }

    return {
      message: 'Bank details updated successfully',
      bankDetails: user.bankDetails,
      status: 200
    };
  }
}
