import { NextResponse } from 'next/server';
import connectToDatabase from '@/app/api/lib/mongodb';
import { Job } from '@/app/api/models/Job';
import { sendEmail } from '@/app/api/lib/email';
import { Referral } from '@/app/api/models/Referral';
import { verifyAuth } from '@/app/api/lib/auth';

// Reusable premium HTML email template builder
function buildEmailHTML(recipientName: string, titleText: string, messageBody: string, detailsHtml: string, ctaHtml: string = '') {
  return `
<!DOCTYPE html>
<html>
<body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;">
  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="table-layout: fixed; background-color: #f8fafc;">
    <tr>
      <td align="center" style="padding: 30px 10px;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #ffffff; border-radius: 20px; overflow: hidden; border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);">
          <!-- Header Banner -->
          <tr>
            <td align="center" style="padding: 35px 40px; background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%); text-align: left;">
              <span style="font-size: 10px; font-weight: 800; text-transform: uppercase; letter-spacing: 2px; color: #93c5fd;">Enterprise HR Portal</span>
              <h1 style="margin: 6px 0 0; font-size: 22px; font-weight: 800; color: #ffffff; letter-spacing: -0.5px;">${titleText}</h1>
            </td>
          </tr>
          <!-- Body Content -->
          <tr>
            <td align="left" style="padding: 40px; background-color: #ffffff;">
              <p style="margin: 0 0 16px; font-size: 15px; color: #0f172a; line-height: 1.6;">Dear <strong>${recipientName}</strong>,</p>
              <p style="margin: 0 0 24px; font-size: 14px; color: #334155; line-height: 1.6;">${messageBody}</p>

              <!-- Details Box -->
              <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
                ${detailsHtml}
              </table>

              ${ctaHtml}

              <p style="margin: 24px 0 0; font-size: 13px; color: #64748b; line-height: 1.6;">Best regards,<br/><strong style="color: #1e3a8a;">HR Talent Acquisition Team</strong></p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td align="center" style="padding: 24px 40px; background-color: #f8fafc; border-top: 1px solid #f1f5f9;">
              <p style="margin: 0 0 6px; font-size: 11px; color: #475569; font-weight: 700; text-transform: uppercase; letter-spacing: 1px;">Enterprise Systems Ltd</p>
              <p style="margin: 0; font-size: 10px; color: #94a3b8; line-height: 1.5;">This email is auto-generated by the recruitment portal. Please do not reply directly to this message.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

// PUT to update job status or details/applicants
export async function PUT(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const decoded = verifyAuth(req);
    if (!decoded) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const { id } = await params;
    const data = await req.json() as any;

    await connectToDatabase();

    const existingJob = await Job.findById(id);
    if (!existingJob) {
      return NextResponse.json({ error: 'Job not found' }, { status: 404 });
    }
    if (existingJob.companyId !== decoded.companyId) {
      return NextResponse.json({ error: 'Forbidden: You do not own this record' }, { status: 403 });
    }

    const oldApplicants = existingJob.applicants || [];
    const newApplicants = data.applicants || [];

    // Find if any applicant changed stage or had an interview scheduled/updated
    for (const newApp of newApplicants) {
      const oldApp = oldApplicants.find((o: any) => o.email === newApp.email || o.name === newApp.name);
      const oldStatus = oldApp ? oldApp.status : null;
      const newStatus = newApp.status;

      const oldInterviews = oldApp ? (oldApp.interviews || []) : [];
      const newInterviews = newApp.interviews || [];

      // Check if a new interview was added or an existing one was modified
      let interviewScheduledOrModified = false;
      let latestInterview = null;

      if (newInterviews.length > 0) {
        latestInterview = newInterviews[newInterviews.length - 1];
        if (newInterviews.length > oldInterviews.length) {
          interviewScheduledOrModified = true;
        } else {
          const oldLatest = oldInterviews[oldInterviews.length - 1];
          if (oldLatest && (
            oldLatest.date !== latestInterview.date || 
            oldLatest.time !== latestInterview.time || 
            oldLatest.interviewer !== latestInterview.interviewer ||
            oldLatest.round !== latestInterview.round
          )) {
            interviewScheduledOrModified = true;
          }
        }
      }

      if ((newStatus && oldStatus !== newStatus) || interviewScheduledOrModified) {
        console.log(`[STAGE_TRANSITION_OR_INTERVIEW] ${newApp.name}: Status: ${oldStatus} -> ${newStatus}, InterviewUpdated: ${interviewScheduledOrModified}`);

        let referral: any = null;
        // Sync corresponding referral status if it exists
        if (newStatus && oldStatus !== newStatus) {
          let referralStatus: 'Submitted' | 'Under Review' | 'Interview Scheduled' | 'Selected' | 'Rejected' | 'Bonus Credited' | null = null;
          if (newStatus === 'Applied') referralStatus = 'Submitted';
          else if (newStatus === 'Screening' || newStatus === 'Shortlisted') referralStatus = 'Under Review';
          else if (newStatus === 'Interview' || newStatus === 'Technical Round' || newStatus === 'HR Round') referralStatus = 'Interview Scheduled';
          else if (newStatus === 'Offer Sent' || newStatus === 'Hired') referralStatus = 'Selected';
          else if (newStatus === 'Rejected') referralStatus = 'Rejected';

          if (referralStatus) {
            try {
              const queryConditions: any[] = [];
              if (newApp.email) queryConditions.push({ candidateEmail: { $regex: new RegExp(`^${newApp.email}$`, 'i') } });
              if (newApp.name) queryConditions.push({ candidateName: { $regex: new RegExp(`^${newApp.name}$`, 'i') } });
              
              if (queryConditions.length > 0) {
                referral = await Referral.findOneAndUpdate(
                  {
                    jobId: id,
                    $or: queryConditions
                  },
                  { status: referralStatus },
                  { new: true }
                );
              }
            } catch (refErr) {
              console.error('Failed to sync referral status in database:', refErr);
            }
          }
        }

        const candidateEmail = (newApp.email && newApp.email.includes('@')) 
          ? newApp.email 
          : (process.env.EMAIL_FROM || 'dipakpatil8589@gmail.com');
        const candidateName = newApp.name;
        const jobTitle = existingJob.title;

        let subject = '';
        let text = '';
        let html = '';

        if (newStatus === 'Applied') {
          subject = `Application Received: ${jobTitle}`;
          text = `Dear ${candidateName},\n\nThank you for your application for the ${jobTitle} position at our organization. We have successfully received your credentials and are currently conducting an initial review.\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Applied Position</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">Current Status</td>
              <td style="font-size: 12px; font-weight: bold; color: #3b82f6; text-transform: uppercase;">Application Received</td>
            </tr>
          `;
          
          html = buildEmailHTML(
            candidateName,
            'APPLICATION RECEIVED',
            `Thank you for expressing interest in joining our team. Your application for the position of <strong>${jobTitle}</strong> has been successfully registered in our applicant tracking system and is awaiting panel screening.`,
            detailsHtml
          );
        }
        else if (newStatus === 'Screening') {
          subject = `Application Update: Screening Stage for ${jobTitle}`;
          text = `Dear ${candidateName},\n\nWe wanted to let you know that your profile for the ${jobTitle} position has been progressed to the Screening stage. Our recruiting panel is reviewing your qualifications and experience details.\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Position</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">Process Stage</td>
              <td style="font-size: 12px; font-weight: bold; color: #f59e0b; text-transform: uppercase;">Candidate Screening</td>
            </tr>
          `;
          
          html = buildEmailHTML(
            candidateName,
            'PROFILE UNDER SCREENING',
            `Your profile has been advanced to the <strong>Screening</strong> phase for the <strong>${jobTitle}</strong> opening. Our hiring coordinators are evaluating your skillsets and will reach out if they require any additional documents.`,
            detailsHtml
          );
        }
        else if (newStatus === 'Shortlisted') {
          subject = `Congratulations! You have been Shortlisted for ${jobTitle}`;
          text = `Dear ${candidateName},\n\nWe are pleased to inform you that your application for the ${jobTitle} position has been Shortlisted!\n\nOur recruitment team will reach out to you shortly for scheduling.\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Position Applied</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Current Status</td>
              <td style="font-size: 12px; font-weight: bold; color: #2563eb; padding-bottom: 8px; text-transform: uppercase;">Shortlisted</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">Action Required</td>
              <td style="font-size: 12px; color: #334155;">None at the moment. Recruitment panel will initiate callback.</td>
            </tr>
          `;
          
          html = buildEmailHTML(
            candidateName,
            'APPLICATION SHORTLISTED',
            `We are pleased to inform you that your profile has been evaluated and successfully <strong>Shortlisted</strong> for the position of <strong>${jobTitle}</strong>. Our panel will contact you shortly to lock your interview slots.`,
            detailsHtml
          );
        } 
        else if (['Interview', 'Technical Round', 'HR Round'].includes(newStatus) || interviewScheduledOrModified) {
          const latestInterview = newApp.interviews && newApp.interviews.length > 0 
            ? newApp.interviews[newApp.interviews.length - 1] 
            : null;
          const dateStr = latestInterview ? `${latestInterview.date} at ${latestInterview.time}` : 'To be confirmed';
          const interviewerName = latestInterview ? latestInterview.interviewer : 'assigned panel';
          const meetingLink = latestInterview ? latestInterview.meetingLink : '';
          const roundName = latestInterview ? latestInterview.round : (newStatus || 'Interview');

          subject = `Interview Scheduled / Updated: ${roundName} for ${jobTitle}`;
          text = `Dear ${candidateName},\n\nYour ${roundName} interview has been scheduled/updated on ${dateStr} with ${interviewerName}.\n\nMeeting Link: ${meetingLink || 'N/A'}\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Interview Round</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${roundName}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Position</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Date & Time</td>
              <td style="font-size: 12px; font-weight: bold; color: #d97706; padding-bottom: 8px;">${dateStr}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">Interviewer</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a;">${interviewerName}</td>
            </tr>
          `;

          const ctaHtml = meetingLink ? `
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
              <tr>
                <td align="center" style="padding-top: 10px; padding-bottom: 10px;">
                  <a href="${meetingLink}" target="_blank" style="display: inline-block; padding: 12px 24px; background-color: #2563eb; color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px;">Join Live Interview Session</a>
                </td>
              </tr>
            </table>
          ` : '';

          html = buildEmailHTML(
            candidateName,
            'INTERVIEW ROUND UPDATED',
            `An interview session has been configured or updated for your candidacy. Please view the schedules below and click the meeting button to join the session at the designated slot.`,
            detailsHtml,
            ctaHtml
          );

          // Notify the Interviewer
          if (latestInterview && latestInterview.interviewer) {
            const interviewerEmail = process.env.EMAIL_FROM || 'dipakpatil8589@gmail.com'; 
            const interviewerSubject = `Urgent Update: Assigned interview for ${candidateName} - ${jobTitle}`;
            const interviewerText = `Hello ${interviewerName},\n\nYou have been assigned/updated as the interviewer for ${candidateName} for the ${roundName} round of ${jobTitle}.\n\nScheduled: ${dateStr}\n\nPlease submit your evaluation scorecard post-interview.\n\nBest regards,\nHR Admin`;
            
            const intDetailsHtml = `
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Candidate Name</td>
                <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${candidateName}</td>
              </tr>
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Email Address</td>
                <td style="font-size: 12px; color: #334155; padding-bottom: 8px;">${newApp.email || 'Not specified'}</td>
              </tr>
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Evaluation Round</td>
                <td style="font-size: 12px; font-weight: bold; color: #2563eb; padding-bottom: 8px;">${roundName}</td>
              </tr>
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b;">Scheduled Slot</td>
                <td style="font-size: 12px; font-weight: bold; color: #d97706;">${dateStr}</td>
              </tr>
            `;

            const intCtaHtml = meetingLink ? `
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td align="center" style="padding-top: 10px; padding-bottom: 10px;">
                    <a href="${meetingLink}" target="_blank" style="display: inline-block; padding: 12px 24px; background-color: #0f172a; color: #ffffff; text-decoration: none; border-radius: 8px; font-weight: bold; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px;">Enter Evaluation Room</a>
                  </td>
                </tr>
              </table>
            ` : '';

            const intHtml = buildEmailHTML(
              interviewerName,
              'INTERVIEWER ASSIGNMENT UPDATED',
              `Your assigned interview session for ${candidateName} for the <strong>${roundName}</strong> round of <strong>${jobTitle}</strong> has been created or updated. Please check the timings below.`,
              intDetailsHtml,
              intCtaHtml
            );

            sendEmail({ 
              to: interviewerEmail, 
              subject: interviewerSubject, 
              text: interviewerText, 
              html: intHtml 
            }).catch(intMailErr => {
              console.error('Failed to send interviewer assignment email:', intMailErr);
            });
          }
        }
        else if (newStatus === 'Offer Sent') {
          subject = `Congratulations! Employment Offer for ${jobTitle}`;
          text = `Dear ${candidateName},\n\nWe are delighted to extend a formal offer of employment for the ${jobTitle} position! We believe you will make a wonderful addition to our organization.\n\nPlease check your email for the detailed offer letter and next steps.\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Offered Designation</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Status</td>
              <td style="font-size: 12px; font-weight: bold; color: #10b981; text-transform: uppercase;">Offer Extended</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">Action Required</td>
              <td style="font-size: 12px; color: #334155;">Please review the digital offer packet and submit your signed acceptance.</td>
            </tr>
          `;
          
          html = buildEmailHTML(
            candidateName,
            'OFFER OF EMPLOYMENT EXTENDED',
            `We are excited to offer you the position of <strong>${jobTitle}</strong>! The recruitment panel was thoroughly impressed by your interviews and technical assessments. We look forward to welcoming you aboard.`,
            detailsHtml
          );
        }
        else if (newStatus === 'Hired') {
          subject = `Offer of Employment: ${jobTitle}`;
          text = `Dear ${candidateName},\n\nWe are thrilled to offer you the position of ${jobTitle} at our organization! Congratulations and welcome aboard.\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Offered Role</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">hiring status</td>
              <td style="font-size: 12px; font-weight: bold; color: #059669; padding-bottom: 8px; text-transform: uppercase;">hired / accepted</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">next steps</td>
              <td style="font-size: 12px; color: #334155;">Onboarding team will trigger contract documents via digital signature.</td>
            </tr>
          `;

          html = buildEmailHTML(
            candidateName,
            'OFFER OF EMPLOYMENT',
            `We are thrilled to offer you the position of <strong>${jobTitle}</strong>! Your technical assessment and panel reviews were outstanding, and we believe you will be a fantastic addition to the team. Congratulations and welcome aboard!`,
            detailsHtml
          );
        }
        else if (newStatus === 'Rejected') {
          subject = `Application Update: ${jobTitle}`;
          text = `Dear ${candidateName},\n\nThank you for your interest in ${jobTitle}. After careful review, we have decided to move forward with other candidates. We wish you the best in your search.\n\nBest regards,\nHR Recruiting Team`;
          
          const detailsHtml = `
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Applied Position</td>
              <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
            </tr>
            <tr>
              <td style="font-size: 12px; font-weight: bold; color: #64748b;">Process Status</td>
              <td style="font-size: 12px; font-weight: bold; color: #dc2626; text-transform: uppercase;">Closed / Completed</td>
            </tr>
          `;

          html = buildEmailHTML(
            candidateName,
            'APPLICATION STATUS COMPLETED',
            `Thank you for taking the time to meet our recruiting panel for the <strong>${jobTitle}</strong> position. While we were impressed with your background, we have decided to proceed with another candidate whose credentials align more closely with our immediate constraints. We will retain your profile for future potential openings.`,
            detailsHtml
          );
        }

        // Send professional email to candidate
        if (subject && candidateEmail) {
          sendEmail({ to: candidateEmail, subject, text, html }).catch(err => {
            console.error('Failed to send candidate transition email:', err);
          });
        }

        // If candidate was referred, notify the employee who referred them (referrer)!
        if (referral && referral.referrerEmail && newStatus && oldStatus !== newStatus) {
          try {
            const referrerSubject = `Referral Update: ${candidateName} has moved to ${newStatus}`;
            const referrerText = `Dear ${referral.referrerName},\n\nWe wanted to let you know that your referred candidate, ${candidateName}, has progressed to the stage: ${newStatus} for the ${jobTitle} position.\n\nThank you for referring top talent to our team!\n\nBest regards,\nHR Recruiting Team`;
            
            const refDetailsHtml = `
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px; width: 30%;">Candidate Name</td>
                <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${candidateName}</td>
              </tr>
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">Position</td>
                <td style="font-size: 12px; font-weight: bold; color: #0f172a; padding-bottom: 8px;">${jobTitle}</td>
              </tr>
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b; padding-bottom: 8px;">New Stage</td>
                <td style="font-size: 12px; font-weight: bold; color: #2563eb; padding-bottom: 8px; text-transform: uppercase;">${newStatus}</td>
              </tr>
              <tr>
                <td style="font-size: 12px; font-weight: bold; color: #64748b;">Incentive Track</td>
                <td style="font-size: 12px; font-weight: bold; color: #10b981;">₹${referral.bonus.toLocaleString()} Reward Pending Status</td>
              </tr>
            `;

            const refHtml = buildEmailHTML(
              referral.referrerName,
              'REFERRAL APPLICATION UPDATE',
              `We are pleased to inform you that your recommended candidate, <strong>${candidateName}</strong>, has progressed to the <strong>${newStatus}</strong> phase of evaluation for the <strong>${jobTitle}</strong> opening. Thank you for helping us grow!`,
              refDetailsHtml
            );

            sendEmail({
              to: referral.referrerEmail,
              subject: referrerSubject,
              text: referrerText,
              html: refHtml
            }).catch(refMailErr => {
              console.error('Failed to send update email to referrer:', refMailErr);
            });
          } catch (refMailErr) {
            console.error('Failed to prepare update email to referrer:', refMailErr);
          }
        }
      }
    }

    const updatedJob = await Job.findByIdAndUpdate(id, data, { new: true });

    if (!updatedJob) {
      return NextResponse.json({ error: 'Job not found' }, { status: 404 });
    }

    return NextResponse.json(
      { message: 'Job updated successfully', job: updatedJob },
      { status: 200 }
    );
  } catch (error: any) {
    console.error('Failed to update job:', error);
    return NextResponse.json({ error: 'Failed to update job', details: error.message }, { status: 500 });
  }
}

// DELETE a job
export async function DELETE(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const decoded = verifyAuth(req);
    if (!decoded) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const { id } = await params;

    await connectToDatabase();

    const existingJob = await Job.findById(id);
    if (!existingJob) {
      return NextResponse.json({ error: 'Job not found' }, { status: 404 });
    }
    if (existingJob.companyId !== decoded.companyId) {
      return NextResponse.json({ error: 'Forbidden: You do not own this record' }, { status: 403 });
    }

    await Job.findByIdAndDelete(id);

    return NextResponse.json(
      { message: 'Job deleted successfully' },
      { status: 200 }
    );
  } catch (error: any) {
    console.error('Failed to delete job:', error);
    return NextResponse.json({ error: 'Failed to delete job', details: error.message }, { status: 500 });
  }
}
